[nixos]
precision-5680-2023-root ansible_host=precision-5680-2023 ansible_user=root
precision-5680-2023-nick ansible_host=precision-5680-2023 ansible_user=nick

[debian]
borg-host ansible_connection=local ansible_user=root
earlgrey-hetzner-vps-1 ansible_host=earlgrey-hetzner-vps-1 ansible_user=root
bioinformatics-host ansible_host=bioinformatics-host ansible_user=root
earlgrey-hetzner-vps-2 ansible_host=earlgrey-hetzner-vps-2 ansible_user=root
data-host ansible_host=data-host ansible_user=root
ai-host ansible_host=ai-host ansible_user=root
